version: "3.8"  # Adjust if needed for your Docker Compose version

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Expose Redis port
    volumes:
      - redis-data:/data  # Persistent volume for Redis data

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"  # Expose Redis Commander port
    environment:
      REDIS_HOSTS: redis:6379  # Connect to Redis service

volumes:
  redis-data:  # Define the Redis data volume
